vim.g.mapleader = ' '
vim.api.nvim_set_keymap('n', '<leader>bj', '<Cmd>bn<Enter>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>bk', '<Cmd>bp<Enter>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>bw', '<Cmd>bwipeout<Enter>', {noremap = true, silent = true})
vim.keymap.set('n', '<leader>dd', vim.diagnostic.open_float)
vim.keymap.set('n', '<leader>dj', vim.diagnostic.goto_next)
vim.keymap.set('n', '<leader>dk', vim.diagnostic.goto_prev)
vim.keymap.set('n', '<leader>ds', vim.diagnostic.setloclist)
vim.api.nvim_set_keymap('n', '<leader>e', 'q:a', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>wh', '<c-w>h', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>wj', '<c-w>j', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>wk', '<c-w>k', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>wl', '<c-w>l', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>w=', '<c-w>=', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>sh', ':vsplit ', {noremap = true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>sv', ':split ', {noremap = true, silent = false})
vim.api.nvim_set_keymap('i', '<c-e>', '<Esc>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('n', '<c-e>', '<Esc>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('s', '<c-e>', '<Esc>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('v', '<c-e>', '<Esc>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<M-o>', '<CR>', {noremap = true, silent = true})
vim.api.nvim_set_keymap('i', '<M-O>', '<Up><End><CR>', {noremap = true, silent = true})
